# Generated by Django 2.1.1 on 2019-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20190329_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='phones'),
        ),
    ]
