# Generated by Django 2.1.1 on 2019-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=64, verbose_name='Тег')),
                ('articles', models.ManyToManyField(related_name='tags', to='articles.Article')),
            ],
        ),
    ]
