# Generated by Django 2.1.1 on 2019-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190408_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='articles.Article'),
        ),
    ]
