# Generated by Django 2.1.1 on 2019-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190412_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='articles.Article'),
        ),
    ]
