# Generated by Django 2.1.1 on 2019-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190412_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='tags',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный'),
        ),
    ]
