# Generated by Django 2.1.1 on 2019-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190412_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='is_main',
            field=models.NullBooleanField(verbose_name='Главный'),
        ),
    ]
