# Generated by Django 2.1.1 on 2019-04-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190412_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='is_main',
            field=models.BooleanField(default=None, verbose_name='Главный'),
        ),
    ]
