# Generated by Django 2.1.3 on 2019-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, verbose_name='Путь к CSV файлу')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('width', models.PositiveIntegerField()),
                ('number_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
