# Generated by Django 2.1.3 on 2019-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='id',
        ),
        migrations.AlterField(
            model_name='path',
            name='path',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Путь к CSV файлу'),
        ),
    ]
