# Generated by Django 2.1.1 on 2019-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название статьи')),
                ('thematic', models.CharField(max_length=256, verbose_name='Тема статьи')),
                ('text', models.TextField(verbose_name='Содержание статьи')),
                ('paid', models.BooleanField(verbose_name='Платная статья')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('vip', models.BooleanField(verbose_name='Платный доступ')),
            ],
        ),
    ]
