# Generated by Django 2.1.1 on 2019-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190422_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameinfo',
            name='attept',
        ),
        migrations.RemoveField(
            model_name='playergameinfo',
            name='player_attempt_id',
        ),
        migrations.AddField(
            model_name='game',
            name='attept_count',
            field=models.IntegerField(default=0, verbose_name='Число попыток'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
