# Generated by Django 2.1.1 on 2019-04-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190423_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='attept_count',
            new_name='attempt_count',
        ),
    ]
